# Generated by Django 5.1.7 on 2025-05-26 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('payments', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0002_alter_saleitem_product_alter_saleitem_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_id', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_payment_purchase', to='purchases.purchase'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_payment_sale', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='updated_by',
            field=models.ForeignKey(help_text='User who updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
