# Generated by Django 5.1 on 2024-09-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchases_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
