# Generated by Django 3.1.14 on 2024-08-27 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mobile Money', 'Mobile Money')], max_length=20)),
                ('payment_for', models.CharField(choices=[('Unknown', 'Unknown'), ('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Unknown', max_length=20)),
                ('related', models.IntegerField(default=265183612631199186295544133719689254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
