# Generated by Django 5.1.7 on 2025-05-12 07:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related', models.IntegerField(default=200766287997268717731366762129674659698)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Credit', 'Credit')], max_length=20)),
                ('payment_for', models.CharField(choices=[('Unknown', 'Unknown'), ('Sale', 'Sale'), ('Purchase', 'Purchase')], default='Unknown', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('fail', 'fail')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
