# Generated by Django 3.1.14 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Credit', 'Credit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=226119644246307417132588528952612008175),
        ),
    ]
