# Generated by Django 3.1.14 on 2024-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20240827_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=301334411334781188750965753693837560486),
        ),
    ]
