# Generated by Django 5.1 on 2024-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=267081910718646740264972872605346611101),
        ),
    ]
