# Generated by Django 5.1 on 2024-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=61498086000550674785143619138381738771),
        ),
    ]
