# Generated by Django 5.1 on 2024-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=45454051788494964077497054975005128794),
        ),
    ]
