# Generated by Django 5.1 on 2024-10-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=281646541319765540592546371343258848857),
        ),
    ]
