# Generated by Django 5.1 on 2024-10-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=337125235637022794300250545721690827906),
        ),
    ]
