# Generated by Django 5.1 on 2024-12-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=111460636466447390710208957039125021705),
        ),
    ]
