# Generated by Django 5.1 on 2024-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=246362619084297315034881163505355679925),
        ),
    ]
