# Generated by Django 5.1 on 2024-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=31634575847466184554116455306854912751),
        ),
    ]
