# Generated by Django 5.1 on 2025-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=252627152852741788928509565524143502811),
        ),
    ]
