# Generated by Django 5.1 on 2025-01-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0040_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=279751810942386754890413414793953199791),
        ),
    ]
