# Generated by Django 5.1 on 2025-01-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=143091966962582119733391176458187936649),
        ),
    ]
