# Generated by Django 5.1 on 2025-01-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=133068530763661913749067644280667039589),
        ),
    ]
