# Generated by Django 5.1 on 2025-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0044_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=282589251328501377313072092503816647249),
        ),
    ]
