# Generated by Django 5.1 on 2025-01-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0045_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=271020052555104758609589577661564980217),
        ),
    ]
