# Generated by Django 5.1 on 2025-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0049_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=191763035386458067965562072847677289024),
        ),
    ]
