# Generated by Django 5.1 on 2025-01-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0053_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=2965670312926988220798157891038788044),
        ),
    ]
