# Generated by Django 5.1 on 2025-02-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0055_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=147489478059616949232567070492989776831),
        ),
    ]
