# Generated by Django 5.1 on 2025-02-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0056_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=160333073375450035133563363402391737470),
        ),
    ]
