# Generated by Django 5.1 on 2025-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0057_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=50241170468207872915642282551091661067),
        ),
    ]
