# Generated by Django 5.1 on 2025-02-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0058_alter_payment_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=125081829788823144467678049580451463683),
        ),
    ]
