# Generated by Django 5.1 on 2025-02-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0059_alter_payment_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('fail', 'fail')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='related',
            field=models.IntegerField(default=77165203300243439393635461842737550454),
        ),
    ]
