# Generated by Django 5.1.7 on 2025-05-29 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_sales', '0002_alter_credit_sale_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_sale',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
        ),
    ]
