# Generated by Django 5.1 on 2024-09-03 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_sales', '0003_alter_credit_sale_due_date_alter_credit_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_sale',
            name='due_date',
            field=models.DateField(default=datetime.date(2024, 9, 13)),
        ),
    ]
