# Generated by Django 5.1 on 2024-12-26 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_sales', '0012_alter_credit_sale_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_sale',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 5)),
        ),
    ]
