# Generated by Django 5.1.7 on 2025-05-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='fallback.png', null=True, upload_to='images/')),
                ('primary_color', models.CharField(help_text='Hex color code (e.g. #FF5733)', max_length=7)),
                ('secondary_color', models.CharField(help_text='Hex color code (e.g. #FF5733)', max_length=7)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
