# Generated by Django 5.1 on 2025-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
