# Generated by Django 5.1 on 2025-02-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='selected',
        ),
    ]
