# Generated by Django 3.1.14 on 2024-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Low Stock', 'Low Stock'), ('Payment Due', 'Payment Due'), ('Top-Up Reminder', 'Top-Up Reminder'), ('Reorder Stock', 'Reorder Stock'), ('Restocked', 'Restocked')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
